# Generated by Django 4.2.13 on 2024-12-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='item_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Goggles Name'),
        ),
    ]
