# Generated by Django 5.2.9 on 2026-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('admin_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Admin ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email ID')),
                ('password', models.CharField(blank=True, max_length=255, verbose_name='Passwors')),
                ('joind_date', models.DateField(blank=True, null=True, verbose_name='Joind Date')),
                ('joind_time', models.TimeField(blank=True, null=True, verbose_name='Joind Time')),
            ],
        ),
    ]
